const createHelper = require('./util/helper');
const path = require('path');
const yaml = require('js-yaml');
const helpers = require('spacedoc-helpers');

/**
 * Create an HTML page out of a documentation object.
 * @param {PageData} data - Page object generated by `Spacedoc.parse()`.
 * @throws Will throw an error if no template was set with `Spacedoc.config()`.
 * @throws Will throw an error if the template encounters an error while rendering.
 * @returns {String} Rendered HTML string.
 */
module.exports = function build(data = {}) {
  // Render a template with the component's data and write it to disk
  let output = '';

  // Create a function to access documentation data for a specific adapter.
  // It's used in the Pug template like this: `spacedoc('adapterName')`
  const helper = createHelper.call(this, data);

  // Extend file data with global data and template locals
  data = Object.assign({}, this.options.data, data, {
    spacedoc: helper,
    helpers,
    site: {
      pages: this.tree,
    },
  });

  // Catch template errors, because they won't show up in the Gulp console
  try {
    output = this.templates.default(data);
  }
  catch (e) {
    console.warn('Spacedoc.build(): ', e);
  }

  if (this.options.keepFm) {
    output = `---\n${yaml.safeDump(data._frontMatter)}\n---\n\n${output}` ;
  }

  return output;
}
